version: "3.9"

services:
  db:
    image: timescale/timescaledb:2.19.0-pg14
    container_name: infosir_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "infosir_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    # Optionally mount a volume for persistent storage
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.10.11
    container_name: infosir_nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js"]  # enable JetStream

  infosir:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infosir_service
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
    environment:
      # We override the config for DB here if needed
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "root"
      DB_PASS: "secret"
      DB_NAME: "infosir_db"

      NATS_URL: "nats://nats:4222"
      # You may also set KLINES_POINT, BINANCE_BASE_URL, etc.
    ports:
      - "8080:8080"
    # Wait for DB and NATS to be ready if needed; can use a small script or service
    # For instance, we can rely on some wait-for-it if desired
    restart: always

volumes:
  db_data:
