version: '3.9'

services:


  # Сервис NATS
  nats:
    image: nats:2.9.19-alpine
    container_name: nats
    ports:
      - "4222:4222"  # основной порт для клиентов (NATS)
      - "8222:8222"  # HTTP-порт для мониторинга NATS
    command: -DV # детальный лог (Debug + Verbose), по желанию
    # Можно добавить переменные окружения NATS, если нужно

  # Сервис InfoSir
  infosir:
    build: .
    container_name: infosir
    depends_on:
      - nats
    # Публикуем порт 8080 наружу
    ports:
      - "8080:8080"
    # Пример передачи ENV-переменных (можно также .env файл в корне)
    environment:
      # Подключимся к NATS по имени контейнера (nats:4222)
      NATS_URL: "nats://nats:4222"
#      NATS_SUBJECT: "infosir_kline"
#      BINANCE_BASE_URL: "https://api.binance.com"
#      PAIRS: "BTCUSDT,ETHUSDT"
#      KLINE_INTERVAL: "1m"
#      KLINE_LIMIT: "10"
      HTTP_PORT: "8080"
      # Можно задать другие переменные

      # NATS_SUBJECT: "infosir_kline"
      # BINANCE_BASE_URL: "https://api.binance.com"
      # Pairs, Interval, и т.д.
      # Если .env лежит рядом, docker-compose может сам их прочитать.

    # Пример healthcheck, обращается к /healthz
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  timescaledb:
    image: timescale/timescaledb:2.11.1-pg15
    container_name: timescaledb
    environment:
      POSTGRES_PASSWORD: mysecret
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data
volumes:
  timescale_data: