version: "3.8"

services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: infosir_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "infosir_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    # Optionally mount a volume for persistent storage
    volumes:
      - db_data:/var/lib/postgresql/data

  nats:
    image: nats:2.9.17-alpine
    container_name: infosir_nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js"]  # enable JetStream

  infosir:
    build: .
    container_name: infosir_app
    depends_on:
      - db
      - nats
    environment:
      # We override the config for DB here if needed
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "root"
      DB_PASS: "secret"
      DB_NAME: "infosir_db"

      NATS_URL: "nats://nats:4222"
      # You may also set KLINES_POINT, BINANCE_BASE_URL, etc.
    ports:
      - "8080:8080"
    # Wait for DB and NATS to be ready if needed; can use a small script or service
    # For instance, we can rely on some wait-for-it if desired

volumes:
  db_data:
